/*
 * Load and save a bunch of strings.
 */

string first = "the first string"
string second = "the second string"
string third = "the third string"
string fourth = "the fourth string"
string fifth = "the fifth string"
string sixth = "the sixth string"

entry
    push first
    push second
    push third
    push fourth
    push fifth
    push sixth
    prints
    pop
    prints
    pop
    prints
    pop
    prints
    pop
    prints
    pop
    prints
    pop
    exit